### ISSUE TITLE
Update dokuwiki to version "hogfather"

### ISSUE THREAD

**Issue by leona-ya** [chaos-jetzt/chaos-jetzt-ansible#26]
Use different plugin management introduced with this version -> update ansible role

**Comment by e1mo** [comment]
In the new "hogfather" Version, Dokuwiki added a CLI to the [extensions plugin](https://www.dokuwiki.org/plugin:extension#command_line_interface). This CLI allows to install and remove extensions. The goal is to switch over the ansible role to this new CLI and add some general improvements.
