### ISSUE TITLE
Eigene venueless-Instanz

### ISSUE THREAD

**Issue by raketenlurch** [chaos-jetzt/chaos-jetzt-ansible#33]
Wir haben uns für's Geekend jetzt für [venueless](https://venueless.org/) als Plattform entschieden. Damit die Server-Kosten nicht privat getragen werden müssen, dahten wir, dass es am sinnvollsten wäre, das zentral aufzusetzten. :)

**Comment by e1mo** [comment]
Was braucht das an requirements (CPU, RAM)?

**Comment by raketenlurch** [comment]
Ich frag mal bei der Orga nach. Wenn ich ne Antwort bekomme sage ich Bescheid,
