### ISSUE TITLE
Do we want to use SSO?

### ISSUE THREAD

**Issue by leona-ya** [chaos-jetzt/chaos-jetzt-ansible#4]
Do we want to use a Single-Sign-On tool for our services? Currently it does not matter which tool we would use.

Please tell us what you think of the idea. Here are some pros and cons I already got:
**Pro:**
* Easy method to get access to services (no need to register with each one and might need different passwords)
  * Easier for users to use a new service

**Con:**
* People are needed to maintain the User-Database (e.g. create new users, delete old, give permissions...)
* Maybe it's not possible to have different e-mail addresses with services
* Difficult for user's who only want an account with one service
* Train user to enter their chaos-jetzt "master-password" at pages who might not use the SSO

**Open questions**
* Is it possible to have different e-mail addresses with services?
* What should happen with already existing accounts?

**Comment by DC7IA** [comment]
Con: If the SSO account gets compromised, all accounts are compromised
Pro: If you know the admins, the access can be restored easily.

**Comment by n0emis** [comment]
If we want to run CodiMD (#7), which I would highly approve on, we *NEED* some kind of Auth-Service.

Another Point for a SSO: through this we could add 2FA to services, which do not natively support this (this would be all of our current services :upside_down_face:).

**Comment by adnidor** [comment]
> If we want to run CodiMD (#7), which I would highly approve on, we _NEED_ some kind of Auth-Service.

Why? CodiMD runs fine without authentication, and has its own auth provider, if authentication is desired

**Comment by n0emis** [comment]
> > If we want to run CodiMD (#7), which I would highly approve on, we _NEED_ some kind of Auth-Service.
> 
> Why? CodiMD runs fine without authentication, and has its own auth provider, if authentication is desired

The integrated Auth-Provider is very limited and does not support features like e.g. lost password or username changes

**Comment by adnidor** [comment]
I am not convinced that we need auth at all for CodiMD. We don't currently use the ACL functionality of the various pads, and I don't see us needing that. Besides ACLs/edit restrictions there is no point in authentication

**Comment by e1mo** [comment]
I think SSO would be quite useful in general. Depending on the tools we may require in the future, we could hook Codi MD (#7) up whilst doing that. But we should configure it in a way that an account is not required for any action but those who want to take advantages of having an account can do so.

**Comment by e1mo** [comment]
> Con: If the SSO account gets compromised, all accounts are compromised
> Pro: If you know the admins, the access can be restored easily.

**Comment by leona-ya** [comment]
It's possible to configure CodiMD to support login via SSO and also "normal" via e-mail and password. I don't think that that's possible for synapse.

**Comment by n0emis** [comment]
> It's possible to configure CodiMD to support login via SSO and also "normal" via e-mail and password. I don't think that that's possible for synapse.

Why would you do that? If we use a SSO, just the SSO should handle Auth and nothing else.

**Comment by n0emis** [comment]
I think what was meant here is, that no auth is needed for any actions. So 
```yaml
codimd_allow_anonymous: true
codimd_allow_anonymous_edits: true
codimd_allow_free_url: true
```
are set.
