### ISSUE TITLE
[Pretix] tickets.chaos.jetzt is not configures

### ISSUE THREAD

**Issue by e1mo** [chaos-jetzt/chaos-jetzt-ansible#49]
The tickets.chaos.jetzt domain is configured as the shop domain for the chaos jetzt organizer but isn't configured in traefik and therefore will serve an invalid SSL certificate. Do we want to keep the tickets. domain and configure it again in traefik or do we want to remove it from pretix and have all cj ticket shops available trough pretix.chaos.jetzt/chaos-jetzt/ ?

**Comment by e1mo** [comment]
I personally would be in favour of keeping the domain since jetzt0 used this url and we would break some old links.

**Comment by n0emis** [comment]
I would be in favor of that too
