### ISSUE TITLE
Mail-Handling - Ticket-System?

### ISSUE THREAD

**Issue by n0emis** [chaos-jetzt/chaos-jetzt-ansible#6]
Currently we use the Zammad, the ticket-system of CTFL for our e-mails. Longterm we may want to do mail handling our own. Therefore we need a way to handle e-mails. **For this issue the relevant problem is only how we want to do handling of e-mails** not who has access to it, this is a problem that should be discussed in plenary.

~ edited by @em0lar

**Comment by adnidor** [comment]
I'd propose a Postfix. We can set aliases for role-accounts and direct a catch-all to a ticket system (propably Zammad)

**Comment by n0emis** [comment]
> I'd propose a Postfix. We can set aliases for role-accounts and direct a catch-all to a ticket system (propably Zammad)

I am not really a fan of hosting our own mailserver. I think we are running just fine with the one from mailbox.org

**Comment by adnidor** [comment]
Why? I think hosting our own mailserver would bring a bunch of advantages, including independence, supporting a dezentralized internet, transparency about our mail handling (via this repo), less cost, and more flexibility.

**Comment by e1mo** [comment]
We're going with freescout as discussed in one of our conferences. The role is already there: https://github.com/chaos-jetzt/ansible-role-freescout and I'm currently deploying it on dev.
