### ISSUE TITLE
Monitoring

### ISSUE THREAD

**Issue by n0emis** [chaos-jetzt/chaos-jetzt-ansible#9]
We’ve had the issue of some outages lately, we only noticed due to the report by other people. therefor i would suggest to set up some kind of monitoring.

**Comment by e1mo** [comment]
I'd propose icinga2 for monitoring since it's quite easy to write custom checks and notification commands. But before we talk about the software to choose, where would we host it, what notification channels should it support, ...?

**Comment by f2k1de** [comment]
What about some kind of NodeExporter, since it can be displayed in many ways (Grafana, …) and it has AlertManager, which can send Events via Mail and to **Matrix**?

**Comment by e1mo** [comment]
Bump that….
@em0lar had the Idea that we could use our two servers (hopper main server and shirley for matrix) to monitor each other.
For our notification channels: How about matrix and also mail and/or something like pagertudy (however that's limited to 5 people in the free tier) for the infra-people?

**Comment by leona-ya** [comment]
Personally, I don't want Paperlike/OpsGenie/... Email should be fine, because it's handled by mailbox.org
